# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler/blob/master/README.md

name: Pull Request Verifier
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run gradle Build
      run: ./gradlew build
  sonar-scan:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run Sonar Scan
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: sonarqube
        arguments: ${{ secrets.SONAR_TOKEN }}
